apiVersion: v1
kind: Service
metadata:
  name: department-service
spec:
  type: LoadBalancer
  selector:
    app: department-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001